### PR TITLE
added google analytics to track usage of extension

### PR DESCRIPTION
**Pull request by tsriram**

### CODE REVIEW

**Comment by siddharthkp** [comment]
@tsriram Is there a way to turn this off?

Not comfortable with 3rd party extensions firing GA events from my twitter. Not sure what information am I making public. (Not an attack on your intentions, just a concern for privacy)

**Comment by tsriram** [comment]
Hmm.. There's no setting to turn this off yet. Wonder if I should be removing this altogether? It gives nothing but a kick to see how many people are using the extension in real time and from where! What say, @siddharthkp?

**Comment by siddharthkp** [comment]
@tsiram, are there any analytics data points that might be useful to capture? 
Recording uninstalls might be helpful if you have a way of reaching out to the guy

**Comment by tsriram** [comment]
@siddharthkp, yeah, that'd be interesting to capture but I don't think Chrome lets you track the user who's uninstalling.

**Pull request merged**
