### PR TITLE
Changed styles in Moments and Moments capsule pages

### PR DESCRIPTION
**Pull request by LauraNK**
Fix for #12.

Fixed the icon color of the Moments icon for all pages. Applied the night theme to the Moments page and  its capsule pages. 

Wasn't quite sure if you wanted me to add the classes to existing styles or separate them. I know you're thinking of cleaning up the Sass, so I opted to put them down at the bottom in their own area. Let me know if you want me to do it another way.

Here's a screenshot of the shiny new design. http://i.imgur.com/4zjVUpF.png

### CODE REVIEW

**Review by tsriram — APPROVED** [review]
LGTM

**Comment by tsriram** [comment]
@LauraNK Thanks a lot again for the fix! What's your twitter handle?

**Comment by LauraNK** [comment]
No problem! I'm excited to get started on the dark theme.
@LauraNKyle :D

**Comment by LauraNK** [comment]
Quick question for you! I'm not entirely sure of github etiquette. I just noticed a small issue with a dark text being almost unreadable on the dark background. Should I submit an issue for it even if I'm willing to patch it myself, or just submit the PR?

**Comment by tsriram** [comment]
Please create a new issue for the same with an understandable description, preferably with a screenshot (especially for this project) and then submit a PR which closes the issue. I'm guessing this is the guideline other projects follow. In any case, I think it makes more sense to follow this so that there's a reference for the issues fixed.

**Pull request merged**
