### PR TITLE
Fixed view of new results block

### PR DESCRIPTION
**Pull request by alxlark**
Fixed issue #10  add stream-container class to build more complex selector. 

As I can see stream-container wraper presents on all pages in twitter

### CODE REVIEW

**Comment by tsriram** [comment]
@alxlark Perfect :+1: Works fine. Just a small thing - can you please move the new styles under the comment `common styles - across all pages`? I'm just keeping all common styles there for easier reference. (this file needs quite a lot of cleanup though :grin: )

**Comment by alxlark** [comment]
@tsriram please review, I put styles in common section

**Comment by tsriram** [comment]
Thank you so much, @alxlark :smile: 

What's your twitter handle?

**Comment by tsriram** [comment]
Closes #10

**Comment by alxlark** [comment]
You are welcome!)

Do you mean twitter account, then [@AlxLark](https://twitter.com/AlxLark)

**Pull request merged**
